#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT"
source .forge_env
source "$ROOT/cap/saved_scripts/shell_scripts/speed_scale.sh"
export OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S="${OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S:-8.0}"
export OPENFORGE_PREVIEW_RECORDER_BACKEND="${OPENFORGE_PREVIEW_RECORDER_BACKEND:-python}"
export OPENFORGE_PREVIEW_RECORDER_REENCODE_H264="${OPENFORGE_PREVIEW_RECORDER_REENCODE_H264:-1}"

OPENFORGE_HOME_DEBUG_PORT="${OPENFORGE_HOME_DEBUG_PORT:-9013}" \
  bash cap/saved_scripts/shell_scripts/home.sh

COMMON_ENV=(
  YAM_STATION_CALIBRATED_XML="${YAM_STATION_CALIBRATED_XML:?Set YAM_STATION_CALIBRATED_XML in .forge_env}"
  CAP_TOP_CAMERA_BACKEND=realsense
  CAP_TOP_CAMERA_FRAME=top_camera_d405
  CAP_TOP_CAMERA_NEEDS_OPTICAL_FLIP=0
  OPENFORGE_ALLOW_PHYSICAL_MOTION=1
)

env "${COMMON_ENV[@]}" \
  OPENFORGE_BOTTLE_RACK_ATTEMPT_BUDGET=1 \
  OPENFORGE_BOTTLE_RACK_HIGH_PLACE_Z_LIFT_M=0.08 \
  OPENFORGE_BOTTLE_RACK_RETREAT_Z_LIFT_M=0.0 \
  OPENFORGE_BOTTLE_RACK_RETREAT_RACK_X_CLEARANCE_M=0.14 \
  OPENFORGE_BOTTLE_RACK_RETREAT_MIN_STANDOFF_M=0.14 \
  OPENFORGE_BOTTLE_RACK_RETREAT_MAX_STANDOFF_M=0.25 \
  OPENFORGE_BOTTLE_RACK_RETREAT_SHIFT_Y_M=0.0 \
  OPENFORGE_BOTTLE_RACK_OPEN_BEFORE_RETREAT_MIN_POS=0.95 \
  OPENFORGE_BOTTLE_RACK_OPEN_BEFORE_RETREAT_TIMEOUT_S=12.0 \
  OPENFORGE_BOTTLE_RACK_OPEN_BEFORE_RETREAT_POLL_S=0.25 \
  OPENFORGE_BOTTLE_RACK_OPEN_BEFORE_RETREAT_RETRY_S=1.5 \
  OPENFORGE_BOTTLE_RACK_GO_HOME_AFTER_PLACE=1 \
  OPENFORGE_BOTTLE_RACK_OPEN_AFTER_HOME=1 \
  OPENFORGE_BOTTLE_RACK_ENABLE_TRANSPORT_WAYPOINTS=1 \
  OPENFORGE_BOTTLE_RACK_TRANSPORT_RACK_X_CLEARANCE_M=0.25 \
  OPENFORGE_BOTTLE_RACK_TRANSPORT_MIN_RETREAT_X_M=0.08 \
  OPENFORGE_BOTTLE_RACK_TRANSPORT_MAX_RETREAT_X_M=0.30 \
  OPENFORGE_BOTTLE_RACK_TRANSPORT_SHIFT_Y_M=-0.28 \
  OPENFORGE_BOTTLE_RACK_TRANSPORT_LIFT_Z_M=0.10 \
  OPENFORGE_BOTTLE_RACK_PLACE_TARGET_MIN_Y_M=0.038 \
  OPENFORGE_BOTTLE_RACK_PLACE_OFFSETS_M='0,0,0;0,0.02,0;0.02,0,0;-0.02,0,0' \
  OPENFORGE_BOTTLE_RACK_ARM=left \
  OPENFORGE_BOTTLE_RACK_FIXED_GRASP_Z_M=0.87414 \
  OPENFORGE_BOTTLE_RACK_LIVE_DETECTION_Z_TO_BODY_OFFSET_M=-0.08 \
  OPENFORGE_BOTTLE_RACK_SIDE_GRASP_BACKOFF_M=-0.020 \
  OPENFORGE_BOTTLE_RACK_SIDE_PREGRASP_CLEARANCE_M=0.100 \
  OPENFORGE_BOTTLE_RACK_SIDE_PREGRASP_XY_BIAS_M=0.000,0.005 \
  OPENFORGE_BOTTLE_RACK_LIFT_Z_M=0.24 \
  OPENFORGE_BOTTLE_RACK_PLANNING_SPEED="${OPENFORGE_BOTTLE_RACK_PLANNING_SPEED:-$(yam_speed_mul 0.40)}" \
  OPENFORGE_BOTTLE_RACK_PLANNER_BACKEND=rrtconnect \
  OPENFORGE_BOTTLE_RACK_CLOSE_SCOUT_POS=0.78 \
  OPENFORGE_BOTTLE_RACK_CLOSE_MID_POS=0.58 \
  OPENFORGE_BOTTLE_RACK_CLOSE_TARGET_POS=0.35 \
  OPENFORGE_BOTTLE_RACK_CLOSE_VEL_LIMIT=0.60 \
  OPENFORGE_BOTTLE_RACK_CLOSE_TORQUE_LIMIT=0.80 \
  OPENFORGE_BOTTLE_RACK_OPEN_VEL_LIMIT=0.50 \
  OPENFORGE_BOTTLE_RACK_OPEN_TORQUE_LIMIT=0.30 \
  uv run python run_script.py \
    script_file=cap/saved_scripts/grasp_lift_place_bottle_rack_one_shot_loop.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=true \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port="${OPENFORGE_BOTTLE_RACK_DEBUG_PORT:-9014}"
