#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
source "$ROOT/cap/saved_scripts/shell_scripts/speed_scale.sh"
export OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S="${OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S:-8.0}"
export OPENFORGE_PREVIEW_RECORDER_BACKEND="${OPENFORGE_PREVIEW_RECORDER_BACKEND:-python}"
export OPENFORGE_PREVIEW_RECORDER_REENCODE_H264="${OPENFORGE_PREVIEW_RECORDER_REENCODE_H264:-1}"

usage() {
  cat <<'USAGE'
Usage: dish_bowl_rack.sh <task>

Tasks:
  white-dish        Place white dish on bottom shelf
  orange-on-white   Put orange dish on top of white dish in bottom rack
  can-trash         Put can in trash
USAGE
}

prepare_runtime() {
  cd "$ROOT"
  # Source with nounset disabled so local/private env files can use optional vars.
  set +u
  source .forge_env
  set -u
}

run_white_dish() {
  prepare_runtime

  YAM_STATION_CALIBRATED_XML="${YAM_STATION_CALIBRATED_XML:?Set YAM_STATION_CALIBRATED_XML in .forge_env}" \
  CAP_TOP_CAMERA_BACKEND=realsense \
  CAP_TOP_CAMERA_FRAME=top_camera_d405 \
  CAP_TOP_CAMERA_NEEDS_OPTICAL_FLIP=0 \
  OPENFORGE_ALLOW_PHYSICAL_MOTION=1 \
  OPENFORGE_BOWL_LOWER_RACK_OBJECT_NAME=white\ dish \
  OPENFORGE_BOWL_RACK_PHYSICAL_TICKET=1 \
  OPENFORGE_BOWL_RACK_OPERATOR_PRESENT=1 \
  OPENFORGE_BOWL_RACK_ESTOP_REACHABLE=1 \
  OPENFORGE_BOWL_RACK_WORKSPACE_CLEAR=1 \
  OPENFORGE_BOWL_RACK_HANDS_TOOLS_CABLES_CLEAR=1 \
  OPENFORGE_BOWL_RACK_FOLLOWER_SERVERS_UP=1 \
  OPENFORGE_BOWL_RACK_NO_OTHER_MOTION_PRECHECK=1 \
  OPENFORGE_BOWL_RACK_RECORDING_DEBUG_CONFIRMED=1 \
  OPENFORGE_BOWL_RACK_WHITE_DISH_VISIBLE=1 \
  OPENFORGE_BOWL_RACK_RACK_CLEAR=1 \
  OPENFORGE_BOWL_RACK_NO_LIQUID=1 \
  OPENFORGE_BOWL_RACK_NO_MANUAL_XYZ=1 \
  OPENFORGE_BOWL_RACK_TICKET_SCOPE=white_dish_bottom_shelf \
  OPENFORGE_BOWL_RACK_PHYSICAL_ATTEMPT_BUDGET=20 \
  OPENFORGE_BOWL_RACK_MAX_ALLOWED_ATTEMPT_BUDGET=20 \
  OPENFORGE_BOWL_RACK_PICKUP_ARM=left \
  OPENFORGE_BOWL_RACK_PICKUP_PROMPTS=white\ dish,dish,white\ plate,plate,dinner\ plate \
  OPENFORGE_BOWL_RACK_OBJECT_DETECTION_PROMPTS=white\ dish,dish,white\ plate,plate,dinner\ plate \
  OPENFORGE_BOWL_RACK_POST_PROMPTS=white\ dish,dish,white\ plate,plate,bottom\ shelf,lower\ shelf,wooden\ rack,rack,blue\ gripper\ fingers \
  OPENFORGE_BOWL_RACK_TARGET_PROMPTS=bottom\ shelf,lower\ shelf,lower\ rack\ shelf,first\ rack\ level,wooden\ rack,rack,wooden\ shelf,shelf \
  OPENFORGE_BOWL_RACK_TARGET_Y_SIGN=negative \
  OPENFORGE_BOWL_RACK_PICKUP_TARGET_Y_SIGN=positive \
  OPENFORGE_BOWL_RACK_REQUIRE_CONTACT_BEFORE_LIFT=0 \
  OPENFORGE_BOWL_RACK_REQUIRE_LIFT_PERCEPTION_BEFORE_PLACE=0 \
  OPENFORGE_BOWL_RACK_GO_HOME_AFTER_SUCCESS=1 \
  OPENFORGE_BOWL_RACK_GO_HOME_AFTER_FAILURE=1 \
  OPENFORGE_BOWL_RACK_OPEN_GRIPPERS_AFTER_HOME=1 \
  OPENFORGE_BOWL_RACK_OPEN_GRIPPERS_AFTER_HOME_SIDES=left,right \
  OPENFORGE_BOWL_RACK_CAPTURE_INTERMEDIATE_OBSERVATIONS=0 \
  OPENFORGE_BOWL_RACK_CAPTURE_POST_PLACE_OBSERVATION=0 \
  OPENFORGE_BOWL_RACK_CLOSE_STEPS=0.30,0.08,0.00 \
  OPENFORGE_BOWL_RACK_CLOSE_TARGET_POS=0.00 \
  OPENFORGE_BOWL_RACK_GRIPPER_SETTLE_S=0.02 \
  OPENFORGE_BOWL_RACK_GRIPPER_CONFIRM_TIMEOUT_S=1.6 \
  OPENFORGE_BOWL_RACK_CLOSE_CONFIRM_TIMEOUT_S=0.6 \
  OPENFORGE_BOWL_RACK_GRIPPER_CONFIRM_POLL_S=0.03 \
  OPENFORGE_BOWL_RACK_GRIPPER_STATE_POLL_S=0.03 \
  OPENFORGE_BOWL_RACK_PLANNING_SPEED="${OPENFORGE_BOWL_RACK_PLANNING_SPEED:-$(yam_speed_mul 0.20)}" \
  OPENFORGE_BOWL_RACK_IK_ERROR_THRESHOLD_M=0.025 \
  OPENFORGE_BOWL_RACK_PICKUP_MAX_CANDIDATES=48 \
  OPENFORGE_BOWL_RACK_PREVIEW_TIMEOUT_S=12 \
  OPENFORGE_BOWL_RACK_EXEC_STALE_CACHE_REPLAN_SLEEP_S=0.05 \
  OPENFORGE_PLATE_RADIUS_OVERRIDE_M=0.1016 \
  OPENFORGE_BOWL_TOP_DOWN_HEIGHT_M=0.0508 \
  OPENFORGE_BOWL_TOP_DOWN_INWARD_TILT_DEG=4.0 \
  OPENFORGE_BOWL_TOP_DOWN_TCP_ABOVE_RIM_M=-0.022 \
  OPENFORGE_BOWL_TOP_DOWN_TCP_ABOVE_RIM_CANDIDATES_M=-0.022,-0.028,-0.016 \
  OPENFORGE_BOWL_TOP_DOWN_LIFT_Z_M=0.140 \
  OPENFORGE_BOWL_TOP_DOWN_LIFT_STEP_M=0.075 \
  OPENFORGE_BOWL_TOP_DOWN_RIM_INWARD_OFFSET_M=-0.005 \
  OPENFORGE_BOWL_TOP_DOWN_RIM_ANGLES_DEG=135,90,45,180,0,-135,-90,-45 \
  OPENFORGE_BOWL_TOP_DOWN_RIM_XY_BIASES_M=0.000,-0.010,0.010 \
  OPENFORGE_BOWL_TOP_DOWN_FINGER_FORWARD_SIGNS=1.0,-1.0 \
  OPENFORGE_BOWL_TOP_DOWN_CLOSE_STEPS=0.30,0.08,0.00 \
  OPENFORGE_BOWL_TOP_DOWN_CLOSE_TARGET_POS=0.00 \
  OPENFORGE_BOWL_LOWER_RACK_TARGET_MODE=shelf_center \
  OPENFORGE_BOWL_LOWER_RACK_TARGET_X_BIAS_M=-0.040 \
  OPENFORGE_BOWL_LOWER_RACK_RELEASE_TCP_X_MAX_M=0.645 \
  OPENFORGE_BOWL_LOWER_RACK_RELEASE_CLEARANCE_M=0.025 \
  OPENFORGE_BOWL_LOWER_RACK_RELEASE_OBJECT_OFFSET_MAX_M=0.240 \
  OPENFORGE_BOWL_LOWER_RACK_OPEN_FRONT=1 \
  OPENFORGE_BOWL_LOWER_RACK_OPEN_FRONT_SLIDE=1 \
  OPENFORGE_BOWL_LOWER_RACK_FRONT_Z_LIFT_M=0.030 \
  OPENFORGE_BOWL_LOWER_RACK_ENTRY_Z_LIFT_M=0.000 \
  OPENFORGE_BOWL_LOWER_RACK_OPEN_FRONT_SLIDE_RELEASE_Z_LIFT_M=0.015 \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_DELTA_DEG=-30.0 \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_DELTA_CANDIDATES_DEG=-30.0 \
  OPENFORGE_BOWL_LOWER_RACK_COMBINE_POST_LIFT_ORIENTATION=1 \
  OPENFORGE_BOWL_LOWER_RACK_UNDO_PICKUP_INWARD_TILT_AFTER_LIFT=1 \
  OPENFORGE_BOWL_LOWER_RACK_PICKUP_INWARD_TILT_UNDO_SIGN=1.0 \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_COMBINED_MAX_ROT_ERROR_DEG=4.0 \
  OPENFORGE_BOWL_LOWER_RACK_REQUIRE_TANGENT_OBJECT_OFFSET=1 \
  OPENFORGE_BOWL_LOWER_RACK_TANGENT_AXIS=x \
  OPENFORGE_BOWL_LOWER_RACK_MIN_TANGENT_ALIGNMENT=0.94 \
  OPENFORGE_BOWL_LOWER_RACK_MAX_CROSS_ALIGNMENT=0.36 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_INSERT_SPLIT_Y_THEN_X=1 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLACE_DOWN_Z=1 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_MAX_IK_ERROR_M=0.030 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_INSERT_Y_ALIGN_MAX_XY_DELTA_M=0.260 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_INSERT_X_MAX_XY_DELTA_M=0.340 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_X_INSERT_MAX_IK_ERROR_M=0.055 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_Z_LIFT_M=0.000 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_Z_LIFT_MAX_Z_DELTA_M=0.010 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_Z_LIFT_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_Z_LIFT_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_X_UP_TILT=1 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_X_UP_TILT_DEG=20.0 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_MAX_TCP_TRANSLATION_M=0.030 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_MAX_ROT_ERROR_DEG=4.0 \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_PLAYBACK_SPEED="${OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_PLAYBACK_SPEED:-$(yam_speed_mul 0.60)}" \
  OPENFORGE_BOWL_LOWER_RACK_PRE_INSERT_TILT_START_INTERP_S=0.60 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLACE_DOWN_MAX_Z_DELTA_M=0.140 \
  OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_Z_LIFT_M=0.100 \
  OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_MAX_Z_DELTA_M=0.130 \
  OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_MAX_IK_ERROR_M=0.055 \
  OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_MAX_XY_DRIFT_M=0.035 \
  OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_AFTER_RELEASE=1 \
  OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_Z_TO_X_RATIO=4.0 \
  OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_MAX_XY_DELTA_M=0.060 \
  OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_MAX_Z_DELTA_M=0.130 \
  OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_DIAGONAL_RETREAT_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_SKIP_X_RETREAT_AFTER_RELEASE_CLEAR=0 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_RETREAT_MAX_IK_ERROR_M=0.045 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_Z_ONLY_MAX_ACTIVE_XY_DRIFT_M=0.012 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_RETREAT_MAX_XY_DELTA_M=0.090 \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_DIRECT_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLACE_DOWN_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLACE_DOWN_STEP_S:-$(yam_speed_div 1.00)}" \
  OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_POST_RELEASE_CLEAR_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_RETREAT_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_DIRECT_RETREAT_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLAYBACK_SPEED="${OPENFORGE_BOWL_LOWER_RACK_DIRECT_PLAYBACK_SPEED:-$(yam_speed_mul 0.60)}" \
  OPENFORGE_BOWL_LOWER_RACK_DIRECT_START_INTERP_S=0.60 \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_STEP_S="${OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_STEP_S:-$(yam_speed_div 0.90)}" \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_PLAYBACK_SPEED="${OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_PLAYBACK_SPEED:-$(yam_speed_mul 0.60)}" \
  OPENFORGE_BOWL_LOWER_RACK_POST_LIFT_J5_START_INTERP_S=0.60 \
  OPENFORGE_BOWL_RACK_RELEASE_CONFIRM_POS=0.55 \
  OPENFORGE_DEBUG_OBS_TIMEOUT_S=5 \
  OPENFORGE_BOWL_RACK_RECORDING_WAIT_S=0.4 \
  OPENFORGE_PLATE_RECORDING_WAIT_S=0.4 \
  OPENFORGE_DEBUG_OBS_CAMERAS=top,left,right,bottom \
  OPENFORGE_DEBUG_OBS_IMAGE_ONLY_CAMERAS=bottom \
  OPENFORGE_BOWL_RACK_IMAGE_ONLY_CAMERAS=bottom \
  uv run python run_script.py \
    script_file=cap/saved_scripts/place_white_dish_on_bottom_shelf_one_shot_loop.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=false \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port=8795
}

run_orange_on_white() {
  prepare_runtime

  YAM_STATION_CALIBRATED_XML="${YAM_STATION_CALIBRATED_XML:?Set YAM_STATION_CALIBRATED_XML in .forge_env}" \
  CAP_TOP_CAMERA_BACKEND=realsense \
  CAP_TOP_CAMERA_FRAME=top_camera_d405 \
  CAP_TOP_CAMERA_NEEDS_OPTICAL_FLIP=0 \
  OPENFORGE_ALLOW_PHYSICAL_MOTION=1 \
  OPENFORGE_BOWL_RACK_PHYSICAL_TICKET=1 \
  OPENFORGE_BOWL_RACK_OPERATOR_PRESENT=1 \
  OPENFORGE_BOWL_RACK_ESTOP_REACHABLE=1 \
  OPENFORGE_BOWL_RACK_WORKSPACE_CLEAR=1 \
  OPENFORGE_BOWL_RACK_HANDS_TOOLS_CABLES_CLEAR=1 \
  OPENFORGE_BOWL_RACK_FOLLOWER_SERVERS_UP=1 \
  OPENFORGE_BOWL_RACK_NO_OTHER_MOTION_PRECHECK=1 \
  OPENFORGE_BOWL_RACK_RECORDING_DEBUG_CONFIRMED=1 \
  OPENFORGE_BOWL_RACK_ORANGE_BOWL_VISIBLE=1 \
  OPENFORGE_BOWL_RACK_WHITE_DISH_VISIBLE=1 \
  OPENFORGE_BOWL_RACK_RACK_CLEAR=1 \
  OPENFORGE_BOWL_RACK_NO_LIQUID=1 \
  OPENFORGE_BOWL_RACK_NO_MANUAL_XYZ=1 \
  OPENFORGE_BOWL_RACK_TICKET_SCOPE=orange_bowl_on_white_bowl_lower_rack \
  OPENFORGE_BOWL_RACK_PHYSICAL_ATTEMPT_BUDGET=20 \
  OPENFORGE_BOWL_RACK_MAX_ALLOWED_ATTEMPT_BUDGET=20 \
  OPENFORGE_DEBUG_OBS_TIMEOUT_S=5 \
  OPENFORGE_DEBUG_OBS_CAMERAS=top \
  OPENFORGE_DEBUG_OBS_IMAGE_ONLY_CAMERAS= \
  OPENFORGE_BOWL_RACK_IMAGE_ONLY_CAMERAS= \
  uv run python run_script.py \
    script_file=cap/saved_scripts/place_orange_bowl_on_white_bowl_lower_rack_one_shot_loop.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=false \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port=8796
}

run_can_trash() {
  prepare_runtime

  YAM_STATION_CALIBRATED_XML="${YAM_STATION_CALIBRATED_XML:?Set YAM_STATION_CALIBRATED_XML in .forge_env}" \
  CAP_TOP_CAMERA_BACKEND=realsense \
  CAP_TOP_CAMERA_FRAME=top_camera_d405 \
  CAP_TOP_CAMERA_NEEDS_OPTICAL_FLIP=0 \
  OPENFORGE_ALLOW_PHYSICAL_MOTION=1 \
  OPENFORGE_CAN_TRASH_PHYSICAL_TICKET=1 \
  OPENFORGE_CAN_TRASH_OPERATOR_PRESENT=1 \
  OPENFORGE_CAN_TRASH_ESTOP_REACHABLE=1 \
  OPENFORGE_CAN_TRASH_WORKSPACE_CLEAR=1 \
  OPENFORGE_CAN_TRASH_HANDS_TOOLS_CABLES_CLEAR=1 \
  OPENFORGE_CAN_TRASH_FOLLOWER_SERVERS_UP=1 \
  OPENFORGE_CAN_TRASH_NO_OTHER_MOTION_PRECHECK=1 \
  OPENFORGE_CAN_TRASH_RECORDING_DEBUG_CONFIRMED=1 \
  OPENFORGE_CAN_TRASH_CAN_VISIBLE=1 \
  OPENFORGE_CAN_TRASH_TRASH_CAN_VISIBLE=1 \
  OPENFORGE_CAN_TRASH_NO_MANUAL_XYZ=1 \
  OPENFORGE_CAN_TRASH_ARM=right \
  OPENFORGE_CAN_TRASH_TRASH_PRIMARY_CAMERAS=top \
  OPENFORGE_CAN_TRASH_REQUIRE_PRIMARY_TRASH_CAMERA=1 \
  OPENFORGE_CAN_TRASH_HIGH_VERTICAL_LIFT_BEFORE_TRANSFER=1 \
  OPENFORGE_CAN_TRASH_DIRECT_DROP_SEQUENCE=1 \
  OPENFORGE_CAN_TRASH_RELEASE_AT_DROP_APPROACH=1 \
  OPENFORGE_CAN_TRASH_RETREAT_AFTER_RELEASE=0 \
  OPENFORGE_CAN_TRASH_TRANSFER_CLEAR_Z_M=1.100 \
  OPENFORGE_CAN_TRASH_TRANSPORT_PREVIEW_MAX_ROT_ERROR_DEG=95.0 \
  uv run python run_script.py \
    script_file=cap/saved_scripts/pick_can_place_in_trash_can_one_shot_loop.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=false \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port=8813
}

task="${1:-}"
case "$task" in
  white-dish|place-white-dish|white-dish-bottom-shelf)
    run_white_dish
    ;;
  orange-on-white|orange-dish|orange-dish-on-white|orange-bowl-on-white)
    run_orange_on_white
    ;;
  can-trash|can-in-trash|trash-can)
    run_can_trash
    ;;
  -h|--help|help|"")
    usage
    ;;
  *)
    echo "Unknown task: $task" >&2
    usage >&2
    exit 2
    ;;
esac
