#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$ROOT"
source .forge_env
source "$ROOT/cap/saved_scripts/shell_scripts/speed_scale.sh"
export OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S="${OPENFORGE_PREVIEW_RECORDER_PROBE_TIMEOUT_S:-8.0}"
export OPENFORGE_PREVIEW_RECORDER_BACKEND="${OPENFORGE_PREVIEW_RECORDER_BACKEND:-python}"
export OPENFORGE_PREVIEW_RECORDER_REENCODE_H264="${OPENFORGE_PREVIEW_RECORDER_REENCODE_H264:-1}"

COMMON_ENV=(
  YAM_STATION_CALIBRATED_XML="${YAM_STATION_CALIBRATED_XML:?Set YAM_STATION_CALIBRATED_XML in .forge_env}"
  CAP_TOP_CAMERA_BACKEND=realsense
  CAP_TOP_CAMERA_FRAME=top_camera_d405
  CAP_TOP_CAMERA_NEEDS_OPTICAL_FLIP=0
  OPENFORGE_ALLOW_PHYSICAL_MOTION=1
)

KITKAT_OBJECT_PROMPTS='kitkat bar,kitkat,KitKat,KitKat wrapper,kit kat,kit kat bar,kit kat wrapper,red KitKat wrapper,red wrapper,small red wrapper,red rectangular wrapper,red rectangular candy wrapper,small red rectangular candy wrapper,red bar,small red bar,red candy bar,red candy wrapper,candy bar,chocolate bar,bar,chocolate,wrapped bar,red chocolate wrapper,red wafer bar,red wafer bar wrapper,red snack wrapper,red package,red packet,small red package,small red packet'
KITKAT_DETECTION_PROMPTS="${KITKAT_OBJECT_PROMPTS},white trash can,trash can,bin,white bowl,bowl,blue gripper fingers"

env "${COMMON_ENV[@]}" \
  OPENFORGE_OPEN_HOME_SPEED_RAD_S="${OPENFORGE_OPEN_HOME_SPEED_RAD_S:-$(yam_speed_mul 0.5)}" \
  OPENFORGE_OPEN_HOME_SETTLE_S="${OPENFORGE_OPEN_HOME_SETTLE_S:-1.0}" \
  uv run python run_script.py \
    script_file=cap/saved_scripts/open_grippers_return_home.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=false \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port="${OPENFORGE_RESET_DEBUG_PORT:-8788}"

env "${COMMON_ENV[@]}" \
  OPENFORGE_CHOCOLATE_HANDOVER_PHYSICAL_TICKET=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_OPERATOR_PRESENT=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_ESTOP_REACHABLE=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_WORKSPACE_CLEAR=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_HANDS_TOOLS_CABLES_CLEAR=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_FOLLOWER_SERVERS_UP=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_NO_OTHER_MOTION_PRECHECK=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_RECORDING_DEBUG_CONFIRMED=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_OBJECT_VISIBLE=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_NO_MANUAL_XYZ=1 \
  OPENFORGE_CHOCOLATE_HANDOVER_PROMPTS="${KITKAT_DETECTION_PROMPTS}" \
  OPENFORGE_CHOCOLATE_HANDOVER_OBJECT_PROMPTS="${KITKAT_OBJECT_PROMPTS}" \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_PROMPTS='white trash can,trash can,bin' \
  OPENFORGE_CHOCOLATE_HANDOVER_CAMERAS=top,left,right,bottom \
  OPENFORGE_CHOCOLATE_HANDOVER_IMAGE_ONLY_CAMERAS=left,right,bottom \
  OPENFORGE_CHOCOLATE_HANDOVER_USE_SAM3_BAR_AXIS=0 \
  OPENFORGE_CHOCOLATE_HANDOVER_BAR_AXIS_XY=0,1 \
  OPENFORGE_CHOCOLATE_HANDOVER_BAR_LENGTH_M=0.140 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_PICK_INSET_M=0.010 \
  OPENFORGE_CHOCOLATE_HANDOVER_TABLE_Z_M=0.760 \
  OPENFORGE_CHOCOLATE_HANDOVER_TOP_DOWN_TCP_ABOVE_TABLE_M=0.030 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_HANDOFF_POS_M=0.560,0.060,0.940 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_RECEIVE_OFFSET_FROM_LEFT_M=0.000,-0.110,-0.030 \
  OPENFORGE_CHOCOLATE_HANDOVER_APPROACH_Z_LIFT_M=0.080 \
  OPENFORGE_CHOCOLATE_HANDOVER_LIFT_Z_M=0.090 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_PRE_STANDOFF_M=0.020 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_PRE_Z_LIFT_M=0.020 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_RETREAT_ACTUAL_Y_M=0.190 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_RETREAT_ACTUAL_Z_M=0.030 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_POST_GRIP_CLEARANCE_OFFSET_FROM_HANDOFF_M=0.000,0.190,0.030 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_RETREAT_AFTER_LEFT_X_M=-0.040 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_RETREAT_AFTER_LEFT_Y_M=-0.045 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_RETREAT_AFTER_LEFT_Z_M=0.015 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_XY_BIAS_M=0.010,-0.035 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_YZ_STAGE_RPY_DEG=0,90,-15 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_RPY_DEG=0,90,0 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_APPROACH_OFFSET_M=-0.240,0.000 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_RETREAT_OFFSET_M=-0.240,0.000 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_RIGHT_TCP_TO_GRIPPER_CENTER_LOCAL_M=0.000,0.000,0.045 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_FIXED_DROP_Z_M=1.120 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_FIXED_TRANSPORT_Z_M=1.160 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_TRANSPORT_Z_LIFT_M=0.300 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_MIN_TRANSPORT_Z_M=1.18 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_MAX_TRANSPORT_Z_M=1.24 \
  OPENFORGE_CHOCOLATE_HANDOVER_TRASH_RETREAT_Z_M=0.080 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_OPEN_GRIPPER=1.0 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_OPEN_GRIPPER=1.0 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_CLOSE_TARGET_POS=0.04 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_CLOSE_TARGET_POS=0.00 \
  OPENFORGE_CHOCOLATE_HANDOVER_LEFT_CLOSE_STEPS=0.04 \
  OPENFORGE_CHOCOLATE_HANDOVER_RIGHT_CLOSE_STEPS=0.00 \
  OPENFORGE_CHOCOLATE_HANDOVER_PLANNER_BACKEND=rrtconnect \
  OPENFORGE_CHOCOLATE_HANDOVER_PLANNING_SPEED="${OPENFORGE_CHOCOLATE_HANDOVER_PLANNING_SPEED:-$(yam_speed_mul 0.30)}" \
  OPENFORGE_CHOCOLATE_HANDOVER_IK_ERROR_THRESHOLD_M=0.025 \
  OPENFORGE_CHOCOLATE_HANDOVER_IK_ROT_THRESHOLD_DEG=16.0 \
  OPENFORGE_CHOCOLATE_HANDOVER_PREVIEW_TIMEOUT_S=25.0 \
  OPENFORGE_CHOCOLATE_HANDOVER_OBS_TIMEOUT_S=30.0 \
  uv run python run_script.py \
    script_file=cap/saved_scripts/handover_chocolate_bar_left_to_right_one_shot_loop.py \
    skill_library_path=cap/saved_scripts/skill_library \
    env.name=yam-real \
    robot=real_yam \
    robot.dashboard=true \
    robot.await_exit=false \
    robot.go_home_on_exit=false \
    runtime.no_cameras=true \
    recording.enabled=true \
    debug_ui.enabled=true \
    debug_ui.auto_open=false \
    debug_ui.auto_exit_on_run_end=false \
    debug_ui.host=0.0.0.0 \
    debug_ui.port="${OPENFORGE_HANDOVER_DEBUG_PORT:-8798}"
